# Generated by Django 3.2.19 on 2023-06-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_actors_films'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
    ]
