# Generated by Django 3.2.19 on 2023-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_actors_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
