# Generated by Django 3.2.19 on 2023-06-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230621_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='alt_tag',
            field=models.CharField(default='actor image', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='alt_tag',
            field=models.CharField(default='film image', max_length=50),
        ),
    ]
