# Generated by Django 3.2.19 on 2023-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230924_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cast',
        ),
        migrations.AddField(
            model_name='post',
            name='cast',
            field=models.ManyToManyField(to='blog.Actor'),
        ),
    ]
