# Generated by Django 3.2.19 on 2023-09-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230924_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cast',
            field=models.ManyToManyField(related_name='actor_list', to='blog.Actor'),
        ),
    ]
