# Generated by Django 3.2.19 on 2023-09-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20230924_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cast',
        ),
        migrations.AddField(
            model_name='post',
            name='cast',
            field=models.ManyToManyField(related_name='actor_list', to='blog.Actor'),
        ),
    ]
